---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-auth-conf
  labels:
{{ include "auth.labels" . | indent 4 }}
data:
  run.sh: |+
{{ tpl (.Files.Get "files/run.sh") . | indent 4 }}

  authservice.conf: |+
{{ tpl (.Files.Get "files/authservice.conf") . | indent 4 }}

  log4j2.xml: |+
{{ tpl (.Files.Get "files/log4j2.xml") . | indent 4 }}