apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cenm
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: pd-balanced

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cenm-shared
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  tier: standard
