---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-idman-conf
  labels:
    {{ include "idman.labels" . | nindent 4 }}
data:
  run.sh: |+
    {{ tpl (.Files.Get "files/run.sh") . | nindent 4 }}

  getZoneToken.sh: |+
    {{ tpl (.Files.Get "files/getZoneToken.sh") . | nindent 4 }}

  identitymanager-init.conf: |+
    {{ tpl (.Files.Get "files/identitymanager-init.conf") . | nindent 4 }}

  log4j2.xml: |+
    {{ tpl (.Files.Get "files/log4j2.xml") . | nindent 4 }}
